apiVersion: v1
kind: Pod
metaData:
  name: db
  labels:
    name: progres-pod
    app: demo-voting-app
spec:
  containers:
  - name: postgres
    image: postgres:9.4
    ports:
      containerPort: 5432