apiVersion: v1
kind: Pod
metaData:
  labels:
    name: result-app-pod
    app: demo-voting-app
spec:
  containers:
  - name: result-app
    image: dockersamples/examplevotingapp_result
    ports:
      containerPort: 80